name: Markdown Lint

on:
  # Run this workflow on push to main
  push:
    branches:
      - main

  # Run this workflow on pull request to main
  pull_request:
    branches:
      - main

jobs:
  markdownlint:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)

    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3
      - name: Markdown Lint
        uses: articulate/actions-markdownlint@v1
