name: Shellcheck

on:
  # Run this workflow on push to main
  push:
    branches:
      - main

  # Run this workflow on pull request to main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)

    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          severity: error
