name: Create and Build app using Ecma Script base

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn --no-progress --non-interactive --no-lockfile
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Create app using Ecma Script base
        run: npx create-react-webpack-project app
      - name: Lint code after build
        run: |
          cd app
          yarn lint:fix
      - name: Build prod bundle
        run: |
          cd app
          yarn build
      - name: Build dev bundle
        run: |
          cd app
          yarn build:dev
