name: Create and Build app using addon/redux

on: [push, pull_request]

jobs:
  redux-es:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn --no-progress --non-interactive --no-lockfile
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
      - name: Create app using Redux
        run: yarn create react-webpack-project app --src-dir=src --redux
      - name: Lint code after build
        run: |
          cd app
          yarn lint:fix
      - name: Build prod bundle
        run: |
          cd app
          yarn build
      - name: Build dev bundle
        run: |
          cd app
          yarn build:dev
  redux-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn --no-progress --non-interactive --no-lockfile
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
      - name: Create app using TypeScript + Redux
        run: yarn create react-webpack-project app --src-dir=src --typescript --redux
      - name: Lint code after build
        run: |
          cd app
          yarn lint:fix
      - name: Build prod bundle
        run: |
          cd app
          yarn build
      - name: Build dev bundle
        run: |
          cd app
          yarn build:dev
  redux-saga-es:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn --no-progress --non-interactive --no-lockfile
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
      - name: Create app using Redux Saga
        run: yarn create react-webpack-project app --src-dir=src --redux --saga
      - name: Lint code after build
        run: |
          cd app
          yarn lint:fix
      - name: Build prod bundle
        run: |
          cd app
          yarn build
      - name: Build dev bundle
        run: |
          cd app
          yarn build:dev
  redux-saga-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn --no-progress --non-interactive --no-lockfile
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
      - name: Create app using TypeScript + Redux Saga
        run: yarn create react-webpack-project app --src-dir=src --typescript --redux --saga
      - name: Lint code after build
        run: |
          cd app
          yarn lint:fix
      - name: Build prod bundle
        run: |
          cd app
          yarn build
      - name: Build dev bundle
        run: |
          cd app
          yarn build:dev
